- hosts: all
  gather_facts: yes
  # user: vagrant
  become: yes
  # pre_tasks:
  # - name: 'atualizando o repo'
  #   raw: 'yum update -y'
  # - name: 'instalando o python para uso do ansible'
  #   raw: 'yum install -y python'
  
- hosts: db
  user: vagrant
  become: yes
  roles:
  - role: linux-config
  - role: cache-prereq
  - role: cache-install
